[gcp_service_account]
type = "service_account"
project_id = "notesapp-471512"
private_key_id = "2e10b35736e31c728854ae39da536446f18ed505"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCf7lPQrMnsUJct\nnQNn7T5R12w8LmpfyXh5HH7Es85GHJ8wEjLUqqKp+Nf+uC+5OtZTZiyh7GFHTsKb\nUs8e2dUlKF7IJfl3CQ925wpKH5uNiVYfhQ1ks66PeNL/NbX3oaLlBNc0xV4PKupG\noY/k9EvZ6b6+VVFn7qRfr1EkPOCSjBS2gCh1EJLWRZ0Uf7J1IbIYWv+96zh7FIL+\nP5Aq472arIJwn87MoOrgrN5oz6S78t/Xt9F8+OuqbXK5/bgsO7/dJCPUmb392Gl+\nyurPzbFwHbNox3y9z1M+OS2D757+CSfK+0G04XrPMMOfYTjjYlKvhF6zydaolv9g\ndaojLuaRAgMBAAECggEACDhfPXwMGuXfh1wpJyfWCq3YZdV66TZ5RzxUNbcKNKdW\n9UkSLMUifDsKmxCLf2lLR9kaFS6Jp3kgXoxokezfXDwRdxcgleI01cc1S68JN0Km\nVxNnJ1Rm9f/fVHfFxRcdQMk5aIB2f7AUf5HhTALUfTxa7fyDpSRqdXKU6JhqcI3G\n1Lu1uOPcoH4ZGGa9OjaCdan1izIpYelRo4xGtt9SkMj/STv7OwD8vzIXdeKhuiza\nSW5O7PMy40FJGMojRhqt8gdgU5Di4g+ar+J9uygZtETh3wHD8+8NhqdCnuAhEGqu\nRwhF5D9xSsKlbEiEgS23ZCdMRwAROzT9NK5CHP3rewKBgQDVE/G/Fl2YJINtgaVX\nA/70eKheU46oFSevpxChbVRDpJphGS1lkaRgSZqgcTm+GL7/DxlbuR8cOKfE8xSF\njk6IoDO02R02kbIA0Gbeo2L6vNJqUmtuyXiGr1vdydpJL2bfpdiXru0q3aKHGO3I\n2ktHhbK5lrXmFeU5GW5cXo8zuwKBgQDAJbAof3Ku+SRK+JbSr9D0GfJ0CGJfOMRQ\njshQpyNfqFudd5LnKRxAZuaRuAtFiTSG5OvMksjWSauCOWwjSO0ZFsN92CtKcBpY\nJwZBx22S/bpO6N1BKX/XVYpDNwFj5r6nAzyCY3uWCVkGE+0Wwryjb4htCs/nWzyq\n+y9e2UE8IwKBgDWZrMhq8eRh2wXjBRqckLgi2gfQcSRrHe6b0h0piXbyozslwDu6\npWTrXxBZKzNcuj8jJzfhm6fXwKxUkab/I1ZPJnKp4yVlBSgbRKVg6Hc2pJ/GV+wo\nlj8bQbrLGjQqznAYIiIWCOctlcLyTG6oKyO0yD7TYLKec2knspFd4BwdAoGAFSXQ\nvpRQXfujx/CWQPgCymr0qVqm4Q4RZUBhwaazmPqhorIfY/u9VUU+CTm1W+De/B3D\n6g8ZtaQEEWAai8Oh/MnpmDcrhJTUAXHCGYlGgRAV6kts1pgnrt6GSiGKsKEbyKvt\ng/hJCNlch/O3e3LRajeDT2UKPs9m3PaqXwkQSfsCgYEAmwszDuWBwgJabnJRyt2K\nU/mAcks/WDlsKeXYlAEgd0UQVZKFv8VWZOO47fUBGWvYPQBNiXjs77kCDVRk0IL0\nK9BaatcsFMKfRuyvjqvJnAL18uqUR4FU8dl/jtDeWILJHJpNFMXDgKKQir5vkg4l\n6E2rI8ZZ1ryedjhpiwwOibU=\n-----END PRIVATE KEY-----\n"
client_email = "notes-service@notesapp-471512.iam.gserviceaccount.com"
client_id = "102978130047449919792"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/notes-service%40notesapp-471512.iam.gserviceaccount.com"

[email]
username = "ffitnessworld9@gmail.com"
password = "xvaqukdlfkahjanp"
send_to = [
  "HayaAls@aramex.com",
  "NoufAls@aramex.onmicrosoft.com",
  "Farismi@aramex.com",
  "fitnessworlf4noon@gmail.com"
]
